export default[
    {
        _id:0,
        author:{
            profile_img_url:"https://upload.wikimedia.org/wikipedia/en/3/35/Supermanflying.png",
            display_name:"Shelton Simbi",
            username:"@sheltonsimbi"
        },
        body:`Ma bishu manyama`,
        stats:{
            likes:['user_1','user_2','user_3','user_4','user_5'],
            retweets:['user_1','user_2','user_3'],
            comments:[
                {
                    username:"@johnwick",
                    body:"persistence"
                },
                {
                    username:"@johnwick1",
                    body:"Consistency"
                },
                {
                    username:"@johnwick2",
                    body:"persistence"
                }
            ]
        }
    },
    {
        _id:1,
        author:{
            profile_img_url:"https://upload.wikimedia.org/wikipedia/en/c/c7/Batman_Infobox.jpg",
            display_name:"John Wick",
            username:"@johnwick"
        },
        body:`Who killed my dog?`,
        stats:{
            likes:['user_1','user_2','user_3','user_4'],
            retweets:['user_1','user_2','user_3','user_4','user_5','user_6'],
            comments:[
                {
                    username:"@johnwick",
                    body:"persistence"
                },
                {
                    username:"@johnwick1",
                    body:"Consistency"
                },
                {
                    username:"@johnwick2",
                    body:"persistence"
                },
                {
                    username:"@johnwick2",
                    body:"persistence"
                },
                {
                    username:"@johnwick2",
                    body:"persistence"
                },
                {
                    username:"@johnwick2",
                    body:"persistence"
                }
            ]
        }
    },
    {
        _id:2,
        author:{
            profile_img_url:"https://upload.wikimedia.org/wikipedia/en/2/21/Web_of_Spider-Man_Vol_1_129-1.png",
            display_name:"Uncle Waffles",
            username:"@unclewaffles"
        },
        body:`Are you guys feeling Tanzania?, chikuhuhuuu`,
        stats:{
            likes:['user_1','user_2','user_3','user_4','user_5'],
            retweets:['user_1','user_2','user_3','user_4'],
            comments:[
                {
                    username:"@johnwick",
                    body:"persistence"
                },
                {
                    username:"@johnwick1",
                    body:"Consistency"
                },
                {
                    username:"@johnwick2",
                    body:"persistence"
                }
            ]
        }
    },
    {
        _id:3,
        author:{
            profile_img_url:"https://upload.wikimedia.org/wikipedia/en/d/d2/Back_to_the_Future.jpg",
            display_name:"Toy Story",
            username:"@toystory"
        },
        body:`Phobia...`,
        image:{
            url:"https://upload.wikimedia.org/wikipedia/en/1/13/Toy_Story.jpg",
            alt:"Toy Story Image"
        },
        stats:{
            likes:['user_1','user_2','user_3','user_4','user_5'],
            retweets:['user_1','user_2','user_3'],
            comments:[
                {
                    username:"@johnwick",
                    body:"persistence"
                },
                {
                    username:"@johnwick1",
                    body:"Consistency"
                },
                {
                    username:"@johnwick2",
                    body:"persistence"
                }
            ]
        }
    }
]